import styles from './MainLayout.module.css';
import Head from 'next/head';
import { FC } from 'react';
import Navbar from '../Navbar';


const MainLayout: FC = ({children}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

  

      <main className={styles.main}>
        {children}                     
      </main>      
    </div>
  )
}

export default MainLayout